# Generated by Django 4.0.4 on 2022-06-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corretores', '0002_alter_corretor_nome_alter_corretor_sobrenome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corretor',
            name='sobrenome',
        ),
        migrations.AlterField(
            model_name='corretor',
            name='nome',
            field=models.CharField(default='Imobiliária', max_length=30),
        ),
    ]
