# Generated by Django 4.0.4 on 2022-06-09 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setores', '0001_initial'),
        ('corretores', '0003_remove_corretor_sobrenome_alter_corretor_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='corretor',
            name='id_setor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setores.setor'),
        ),
    ]
