# Generated by Django 4.0.4 on 2022-06-09 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corretores', '0004_corretor_id_setor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corretor',
            old_name='id_setor',
            new_name='setor',
        ),
    ]
