# Generated by Django 4.0.4 on 2022-06-10 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setores', '0011_rename_user_setor_usuario'),
        ('corretores', '0007_alter_corretor_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corretor',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setores.setor'),
        ),
    ]
