# Generated by Django 4.0.4 on 2022-06-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setor',
            name='nome_setor',
            field=models.CharField(default='Imobiliária', max_length=30),
        ),
    ]
