# Generated by Django 4.0.4 on 2022-06-09 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setores', '0008_alter_setor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setor',
            name='user',
        ),
    ]
