# Generated by Django 4.0.4 on 2022-06-09 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setores', '0010_setor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setor',
            old_name='user',
            new_name='usuario',
        ),
    ]
