# Generated by Django 4.0.4 on 2022-06-18 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('corretores', '0009_corretor_usuario'),
        ('setores', '0012_alter_setor_nome_setor'),
        ('chaves', '0007_remove_chave_horario'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retirada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField(auto_now_add=True)),
                ('chave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chaves.chave')),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretores.corretor')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setores.setor')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_retirada',
            },
        ),
    ]
