# Generated by Django 4.0.4 on 2022-06-21 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_retirada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Retirada',
        ),
    ]
