# Generated by Django 4.0.4 on 2022-06-09 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corretores', '0004_corretor_id_setor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3)),
                ('codigo_imovel_crm', models.CharField(max_length=30)),
                ('id_corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corretores.corretor')),
            ],
            options={
                'db_table': 'tb_chaves',
            },
        ),
    ]
