# Generated by Django 4.0.4 on 2022-06-09 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chave',
            old_name='id_corretor',
            new_name='corretor',
        ),
    ]
