# Generated by Django 4.0.4 on 2022-06-09 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setores', '0002_alter_setor_nome_setor'),
        ('chaves', '0002_rename_id_corretor_chave_corretor'),
    ]

    operations = [
        migrations.AddField(
            model_name='chave',
            name='setor_atribuido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setores.setor'),
        ),
    ]
