# Generated by Django 4.0.4 on 2022-06-15 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setores', '0012_alter_setor_nome_setor'),
        ('corretores', '0009_corretor_usuario'),
        ('chaves', '0004_chave_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chave',
            name='codigo_imovel_crm',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='chave',
            name='corretor',
            field=models.ForeignKey(default='Imobiliária', on_delete=django.db.models.deletion.CASCADE, to='corretores.corretor'),
        ),
        migrations.AlterField(
            model_name='chave',
            name='setor_atribuido',
            field=models.ForeignKey(default='Administrativo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='setores.setor'),
        ),
    ]
