# Generated by Django 4.0.4 on 2022-06-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0006_chave_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chave',
            name='horario',
        ),
    ]
