# Generated by Django 4.0.4 on 2022-06-21 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corretores', '0009_corretor_usuario'),
        ('chaves', '0008_chave_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chave',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='chave',
            name='corretor',
            field=models.ForeignKey(default='Imobiliária', null=True, on_delete=django.db.models.deletion.SET_NULL, to='corretores.corretor'),
        ),
    ]
