# Generated by Django 4.0.4 on 2022-06-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0012_alter_chave_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chave',
            name='horario',
            field=models.DateTimeField(blank=True),
        ),
    ]
