# Generated by Django 4.0.4 on 2022-07-04 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chaves', '0014_alter_chave_horario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chave',
            options={'get_latest_by': 'horario'},
        ),
    ]
