# Generated by Django 4.0.4 on 2022-07-05 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setores', '0014_alter_setor_nome_setor'),
        ('corretores', '0010_alter_corretor_setor'),
        ('chaves', '0016_alter_chave_corretor_alter_chave_setor_atribuido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chave',
            name='corretor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='corretores.corretor'),
        ),
        migrations.AlterField(
            model_name='chave',
            name='setor_atribuido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setores.setor'),
        ),
    ]
